//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.StarWars.Presentation.UI.MainConsoleApp.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KS.StarWars.Presentation.UI.MainConsoleApp.Shared.ConsoleMessages", typeof(ConsoleMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance must be a valid decimal number.
        /// </summary>
        internal static string ERROR_DISTANCE_MUST_BE_DECIMAL {
            get {
                return ResourceManager.GetString("ERROR_DISTANCE_MUST_BE_DECIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance value is too big.
        /// </summary>
        internal static string ERROR_VALUE_TOO_BIG {
            get {
                return ResourceManager.GetString("ERROR_VALUE_TOO_BIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;exit&apos; and press ENTER to close R2-D2 travel log..
        /// </summary>
        internal static string INFO_EXIT_HELP {
            get {
                return ResourceManager.GetString("INFO_EXIT_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ############# Welcome to R2-D2 travel log #############.
        /// </summary>
        internal static string INFO_GREETINGS {
            get {
                return ResourceManager.GetString("INFO_GREETINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type the Space Trip distance: .
        /// </summary>
        internal static string INFO_REQUEST_ENTRY_FROM_USER {
            get {
                return ResourceManager.GetString("INFO_REQUEST_ENTRY_FROM_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting BB-8 help to plan resupply stops....
        /// </summary>
        internal static string INFO_REQUESTING_BB8_HELP {
            get {
                return ResourceManager.GetString("INFO_REQUESTING_BB8_HELP", resourceCulture);
            }
        }
    }
}
